README.md
=> Update LICENSE description

src/App.tsx, src/components/Dropdown.tsx, src/components/DropdownIcon.tsx, src/components/Navbar.tsx, src/components/constant.ts
This PR adds a dropdown menu to the features nav-item.
---
=> feat: add dropdown menu

README.md, index.html, package-lock.json, package.json
- Change project name to `HamroNepse`
=> Update project name

README.md
- Add acknowledgement for logo
=> Add acknowledgement

README.md
- Add emoji for acknowledgement
=> Add emoji for acknowledgement

package-lock.json, package.json, src/App.tsx, src/components/Services/Service.jsx, src/constant.ts
This PR adds the services page which includes different list of features but its functionality is yet to be implemented.
---
---
=> Features / Our Services Page

src/components/Banner/index.tsx
color of the buttons has been updated to match the logo
Closes none
This PR changes the color of the buttons to match the logo.
---
=> Refactor: update color of buttons

.github/workflows/eslint.yml
=> Fix: eslint configuration

.github/workflows/eslint.yml
=> Revert changes

src/components/Banner/BannerTable.tsx
This PR enables the dark mode support for the banner table. 
---
=> Feat: Enable dark mode support for banner table

package-lock.json
=> Minor update

src/components/Banner/BannerTable.tsx, src/components/Footer/FooterItem.tsx, src/components/Footer/index.tsx, src/components/Navbar/NavItem.tsx, src/components/Navbar/SubMenu.tsx, src/components/Navbar/index.tsx
=> Refactor code

.github/workflows/eslint.yml
=> Update eslint config

src/App.tsx, src/components/Banner/index.tsx, src/components/Footer/FooterItem.tsx, src/components/Footer/index.tsx, src/components/Navbar/NavItem.tsx, src/components/Navbar/SearchBar.tsx, src/components/Navbar/SubMenu.tsx, src/components/Navbar/index.tsx, src/components/Services/index.tsx, src/components/ShareCalculator/index.tsx, src/constant.ts, src/pages/AboutPage/index.tsx, src/pages/ChartPage/index.tsx, src/pages/ChartsPage/index.tsx, src/pages/ContactPage/index.tsx, src/pages/PrivacyPolicyPage/index.tsx, src/pages/index.tsx
=> Increase route coverage

package-lock.json, package.json, src/components/Chart/index.tsx, src/components/index.ts, src/constant.ts, src/pages/ChartPage/index.tsx, src/pages/HomePage/index.tsx
- Chart Integration
- Code refactoring
=> Chart Integration

.github/workflows/eslint.yml, package.json
=> Fix: Eslint Issue

src/components/Chart/index.tsx
This PR fixes the multiple rendering of the charts
---
=> Fix: multiple rendering of the charts has been fixed

package-lock.json, package.json, tailwind.config.js
- Configure Poppins as default font family
---
=> Configure Poppins as default font family

src/components/ShareCalculator/index.tsx
=> Feature: Enhance share calculator

src/components/ShareCalculator/index.tsx
=> Format code

src/App.tsx, src/components/Footer/index.tsx, src/constant.ts, src/pages/MarketWatchPage/index.tsx, src/pages/ServicesPage/constants.tsx, src/pages/index.tsx
- Minor code improvement
- New feature/service for market match
=> Feature: Market Watch

src/App.tsx, src/components/AdvanceTable/AdvanceTable.tsx, src/components/AdvanceTable/index.tsx, src/components/SimpleTable/SimpleTable.tsx, src/components/SimpleTable/index.tsx, src/components/index.ts, src/main.tsx, src/pages/HomePage/index.tsx
- Put `ThemeProvider` at top level
- Make separate components for simple and advance table
- Refactor code
=> ThemeProvider at top level

src/components/Navbar/SearchBar.tsx, src/components/Navbar/index.tsx, src/components/SimpleTable/SimpleTable.tsx, src/components/SimpleTable/index.tsx
=> Refactor simple table

src/App.tsx, src/components/Login/LoginItem.tsx, src/components/Login/index.tsx, src/components/Navbar/LoginSignupItem.tsx, src/components/Navbar/index.tsx, src/components/Signup/SignupItem.tsx, src/components/Signup/index.tsx, src/constant.ts, src/pages/LoginAndSignupPage/index.tsx, src/pages/index.tsx
This feature will add login and signup page.
---
=> Login and Signup Page

package-lock.json, package.json, src/components/AdvanceTable/AdvanceTable.tsx, src/components/AdvanceTable/index.tsx, src/pages/MarketWatchPage/index.tsx
This PR will add a page in which users will be able to see latest market data.
---
=> Market Watch

src/pages/MarketWatchPage/index.tsx, src/pages/MarketWatchPage/useMarketWatchPage.ts
- Add date when the stock was last updated
=> Add date when the stock was last updated

src/components/AdvanceTable/index.tsx, src/components/Footer/index.tsx, src/components/Login/index.tsx, src/components/Navbar/index.tsx, src/components/Signup/index.tsx
=> Improvise Code

src/components/Contact/index.tsx, src/pages/ContactPage/index.tsx
This PR adds contact for to the project
---
=> feat: add contact page to project

src/components/About/index.tsx, src/pages/AboutPage/index.tsx
This PR adds about us page to the project. 
---
=> feat: add about us page to the project

src/components/PrivacyPolicy/index.tsx, src/pages/PrivacyPolicyPage/index.tsx
This PR adds privacy policy page to the project. 
---
=> feat: add privacy policy page to the project

src/components/Footer/index.tsx, src/components/Navbar/LoginAndSignup.tsx, src/components/Navbar/SearchBar.tsx, src/components/Navbar/index.tsx, src/pages/HomePage/index.tsx
=> Improve Footer UI

.github/workflows/deploy.yml, src/store/AppDataProvider.tsx, vite.config.ts
- Update router config for CI/CD
=> Update router config

.husky/pre-push, package-lock.json, package.json, src/components/Breadcrumb/index.tsx, src/components/Navbar/NavItem.tsx, src/components/Navbar/SearchBar.tsx, src/components/Navbar/SubMenu.tsx, src/components/Navbar/index.tsx, src/components/index.ts, src/pages/HomePage/index.tsx, src/pages/HomePage/useHomePage.ts, src/useAppData.tsx
- Add new package: `branch-naming-check`
- Configure husky to check branch name on push
- UI improvements
- Code refactor
=> Project Setup

src/components/ForgotPassword/index.tsx, src/components/Login/index.tsx
=> Fix: UI issue

src/store/AppDataProvider.tsx
- Send credentials (cookies) along with request
=> Send credentials (cookies) along with request

package-lock.json, package.json
=> Add react-select package

src/components/Navbar/Search.tsx, src/pages/CompanyDetailPage/index.tsx
=> Fix: URL breakage issue

src/components/SimpleChart/index.tsx, src/components/StockDetail/index.tsx, src/pages/CompanyDetailPage/index.tsx
- Replace dummy data with data fetched from API
---
=> Display real-time data

src/pages/CompanyDetailPage/index.tsx
- Set empty array if error fetching data
=> Fix: Set empty array if error fetching data

src/components/Navbar/UserProfile.tsx, src/components/Navbar/UserProfileMenu.tsx, src/components/Navbar/index.tsx, src/store/constant.ts
This PR adds the avatar dropdown for the logged in users.
---
=> Add avatar dropdown

src/store/AppDataProvider.tsx
=> Fix: API call

src/components/Navbar/useNavbar.tsx
=> Fix: signout issue

src/components/Login/useLoginForm.tsx
- `revert`: data removed from login
=> revert: data removed from login

src/components/Navbar/useNavbar.tsx
- update: after sign out, do not redirect or reload
=> update: after sign out, do not redirect or reload

src/components/Navbar/UserProfile.tsx, src/components/Navbar/UserProfileMenu.tsx, src/store/constant.ts
=> Improve Avatar Dropdown UI

src/components/PortfolioTracker/index.tsx, src/components/index.ts, src/pages/PortfolioTrackerPage/index.tsx
=> add: portfolio tracker

src/components/Navbar/Search.tsx
- update: reduce search bar width
=> update: reduce search bar width

src/components/Navbar/UserProfile.tsx, src/components/Navbar/UserProfileMenu.tsx
=> Remove unwanted code

package-lock.json, package.json
- Add `depcheck` to analyze packages
- Remove `tanstack react query` unused package
---
=> Manage Packages

src/components/Navbar/Search.tsx
- Fix: z-index of search suggestions
=> Fix: z-index of search suggestions

src/components/Navbar/Search.tsx, src/components/StockDetail/index.tsx, src/pages/CompanyDetailPage/index.tsx
- Fix: responsiveness and code refactoring
=> Fix: responsiveness and code refactoring

package-lock.json, package.json, src/components/Table/EditableTable/index.tsx
- Update: table options for portfolio tracker
=> Update: table options for portfolio tracker

src/components/ShareCalculator/index.tsx
=> refactor: improve UI

src/components/Table/EditableTable/types.tsx, src/components/Table/EditableTable/useEditableTableData.tsx, src/components/Table/EditableTable/usePortfolio.tsx
- fix: portfolio stock display
=> fix: portfolio stock display

src/components/Table/EditableTable/types.tsx, src/components/Table/EditableTable/useEditableTableData.tsx, src/components/Table/EditableTable/usePortfolio.tsx
Reverts ChandraByte/hamro-nepse#165
=> Revert "fix: portfolio stock display"

src/components/Table/EditableTable/useEditableTableData.tsx, src/components/Table/EditableTable/usePortfolio.tsx
- fix: portfolio stock list display
=> fix: portfolio stock list display

src/components/Table/EditableTable/index.tsx, src/components/Table/EditableTable/types.tsx, src/components/Table/EditableTable/useEditableTable.tsx, src/components/Table/EditableTable/useEditableTableData.tsx, src/components/Table/EditableTable/usePortfolio.tsx
=> feat: stock portfolio

src/pages/ServicesPage/constants.tsx, src/store/constant.ts
=> update: services list

src/components/Table/EditableTable/useEditableTableData.tsx, src/components/Table/EditableTable/usePortfolio.tsx
- Add profit / loss
- Change column name: `Total` to `Amount`
---
=> refactor: protfolio table

src/components/Table/EditableTable/usePortfolio.tsx, src/store/AppDataProvider.tsx
- fix: disable some form fields, improve ui
=> fix: disable some form fields, improve ui

src/index.css
- hide disabled field
- add CSS comments
=> Fix: Portfolio Table

src/index.css
=> remove: font family

src/components/Navbar/LoginAndSignup.tsx, src/components/Navbar/NavItem.tsx, src/components/Navbar/Search.tsx, src/components/Navbar/SubMenu.tsx, src/components/Navbar/UserProfileMenu.tsx, src/components/Navbar/types.tsx
=> Refactor: navbar data type

src/pages/InvestingCalendarPage/index.tsx
=> test: api endpoint

src/pages/InvestingCalendarPage/index.tsx
Reverts ChandraByte/hamro-nepse#184
=> Revert "test: api endpoint"

src/store/constant/navItems.tsx
=> reorder service list
